#!/usr/bin/env python3
from sys import stdin
from base64 import b64encode
from os import _exit
import furl
import afl
afl.init()

url_string = stdin.read()
parsed_url = furl.furl(url_string)

result = {}
result["scheme"] = parsed_url.scheme
result["userinfo"] = (f"{parsed_url.username}" if parsed_url.username is not None else "") + (f":{parsed_url.password}" if parsed_url.password is not None else "")
result["host"] = parsed_url.host
result["port"] = str(parsed_url.port) if parsed_url.port is not None else ""
result["path"] = str(parsed_url.path)
result["query"] = str(parsed_url.query)
result["fragment"] = str(parsed_url.fragment)

print("{" + ",".join(f"\"{k}\":\"{b64encode(result[k].encode('utf-8')).decode('ascii') if result[k] is not None else ''}\"" for k, v in result.items()) + "}", flush=True)
_exit(0)
