#!/usr/bin/env python3
from sys import stdin
from base64 import b64encode
from os import _exit
import urllib3
import afl
afl.init()

url_string = stdin.read()
parsed_url = urllib3.util.parse_url(url_string)

result = {}
result["scheme"] = parsed_url.scheme
result["userinfo"] = parsed_url.auth
result["host"] = parsed_url.host
result["port"] = str(parsed_url.port) if parsed_url.port is not None else ""
result["path"] = parsed_url.path
result["query"] = parsed_url.query
result["fragment"] = parsed_url.fragment

print("{" + ",".join(f"\"{k}\":\"{b64encode(result[k].encode('utf-8')).decode('ascii') if result[k] is not None else ''}\"" for k, v in result.items()) + "}", flush=True)
_exit(0)
