#!/usr/bin/env python3
from sys import stdin
from base64 import b64encode
from os import _exit
import yarl
import afl
afl.init()

url_string = stdin.read()
parsed_url = yarl.URL(url_string)

result = {}
result["scheme"] = parsed_url.scheme
result["userinfo"] = (parsed_url.user if parsed_url.user is not None else "") + (f":{parsed_url.password}" if parsed_url.password is not None else "")
result["host"] = parsed_url.raw_host
result["port"] = str(parsed_url.explicit_port) if parsed_url.explicit_port is not None else ""
result["path"] = parsed_url.raw_path
result["query"] = parsed_url.raw_query_string
result["fragment"] = parsed_url.fragment

print("{" + ",".join(f"\"{k}\":\"{b64encode(result[k].encode('utf-8')).decode('ascii') if result[k] is not None else ''}\"" for k, v in result.items()) + "}", flush=True)
_exit(0)
